=== fluxitsoft/jqa/jqa-parent/jqa-ctx-factory-xmlbeans/src/main/resources/schema/ruleset.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:jqa="http://www.fluxit.com.ar/jqa/schema/ruleset" xmlns:xsd="http://www.w3.org/2001/XMLSchema" ecore:nsPrefix="jqa" ecore:package="jqa" targetNamespace="http://www.fluxit.com.ar/jqa/schema/ruleset">
  <xsd:element ecore:ignore="true" name="Ruleset" type="jqa:Ruleset"/>
  <xsd:complexType name="Ruleset">
    <xsd:sequence>
      <xsd:element ecore:resolveProxies="true" maxOccurs="unbounded" name="rule" type="jqa:Rule"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="Rule">
    <xsd:sequence>
      <xsd:element ecore:resolveProxies="true" name="filterPredicate" type="jqa:Predicate"/>
      <xsd:element ecore:resolveProxies="true" name="checkPredicate" type="jqa:CheckPredicate"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="message" type="xsd:string" use="required"/>
    <xsd:attribute ecore:unsettable="false" name="priority" type="xsd:int"/>
    <xsd:attribute ecore:unsettable="false" name="bidirectionalCheck" type="xsd:boolean"/>
  </xsd:complexType>
  <xsd:complexType abstract="true" name="Predicate">
    <xsd:attribute name="name" type="xsd:string"/>
  </xsd:complexType>
  <xsd:complexType name="ContextProvidedPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:Predicate">
        <xsd:attribute name="predicateName" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="AbstractionPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:CheckPredicate">
        <xsd:attribute ecore:unsettable="false" name="abstractionType" type="jqa:AbstractionType" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:simpleType name="AbstractionType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="ABSTRACT"/>
      <xsd:enumeration value="INTERFACE"/>
      <xsd:enumeration value="CONCRETE"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="AllocationPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:CheckPredicate">
        <xsd:sequence>
          <xsd:element ecore:resolveProxies="true" name="predicate" type="jqa:Predicate"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="NamingPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:CheckPredicate">
        <xsd:attribute name="namePattern" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="ThrowingPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:CheckPredicate">
        <xsd:sequence>
          <xsd:element ecore:resolveProxies="true" name="predicate" type="jqa:Predicate"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="TypingPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:CheckPredicate">
        <xsd:sequence>
          <xsd:element ecore:resolveProxies="true" name="predicate" type="jqa:Predicate"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="UsagePredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:CheckPredicate">
        <xsd:sequence>
          <xsd:element ecore:resolveProxies="true" name="predicate" type="jqa:Predicate"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType abstract="true" name="VarArgsLogicPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:Predicate">
        <xsd:sequence>
          <xsd:element ecore:resolveProxies="true" maxOccurs="unbounded" name="predicate" type="jqa:Predicate"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="AndPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:VarArgsLogicPredicate"/>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="FalsePredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:Predicate"/>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="NotPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:Predicate">
        <xsd:sequence>
          <xsd:element ecore:resolveProxies="true" name="predicate" type="jqa:Predicate"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="OrPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:VarArgsLogicPredicate"/>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="TruePredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:Predicate"/>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="XORPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:VarArgsLogicPredicate"/>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType abstract="true" ecore:interface="true" name="CheckPredicate">
    <xsd:complexContent>
      <xsd:extension base="jqa:Predicate"/>
    </xsd:complexContent>
  </xsd:complexType>
</xsd:schema>

=== fluxitsoft/jqa/jqa-parent/jqa-test-project/src/test/resources/test_ruleset.xml
<?xml version="1.0" encoding="UTF-8"?>
<jqa:Ruleset name=""
	xmlns:jqa="http://www.fluxit.com.ar/jqa/schema/ruleset" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fluxit.com.ar/jqa/schema/ruleset http://jqa-project.googlecode.com/svn/trunk/jqa-parent/jqa-ctx-factory/src/main/resources/schema/ruleset.xsd ">

	<!--	<rule name="Dummy">-->
	<!--		<filterPredicate xsi:type="jqa:TruePredicate" />-->
	<!--		<checkPredicate xsi:type="jqa:TruePredicate" />-->
	<!--	</rule>-->

	<!-- DAO rules	-->
	<rule name="DAO contract naming">
		<filterPredicate xsi:type="jqa:AndPredicate">
			<predicate xsi:type="jqa:TypingPredicate" parentClassName="ar.com.fluxit.jqa.test.fmk.dao.DAO" />
			<predicate xsi:type="jqa:AbstractionPredicate"
				abstractionType="INTERFACE" />
		</filterPredicate>
		<checkPredicate xsi:type="jqa:AndPredicate">
			<predicate xsi:type="jqa:NamingPredicate" classNamePattern="**.dao.*DAO" />
		</checkPredicate>
	</rule>
	<rule name="DAO contract naming">
		<filterPredicate xsi:type="jqa:NamingPredicate"
			classNamePattern="**DAO" />
		<checkPredicate xsi:type="jqa:AndPredicate">
			<predicate xsi:type="jqa:TypingPredicate" parentClassName="ar.com.fluxit.jqa.test.fmk.dao.DAO" />
			<predicate xsi:type="jqa:AbstractionPredicate"
				abstractionType="INTERFACE" />
		</checkPredicate>
	</rule>
	<rule name="Cant use XStream">
		<filterPredicate xsi:type="jqa:TruePredicate" />
		<checkPredicate xsi:type="jqa:UsagePredicate">
			<filterPredicate xsi:type="jqa:TypingPredicate"
				parentClassName="com.thoughtworks.xstream" />
		</checkPredicate>
	</rule>

</jqa:Ruleset>

=== fluxitsoft/jqa/jqa-parent/jqa-test-parent/rules/dao.rset.xml
<?xml version="1.0" encoding="UTF-8"?>
<jqa:Ruleset name="Sample ruleset"
	xmlns:jqa="http://www.fluxit.com.ar/jqa/schema/ruleset" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fluxit.com.ar/jqa/schema/ruleset http://jqa-project.googlecode.com/svn/trunk/jqa-parent/jqa-ctx-factory/src/main/resources/schema/ruleset.xsd ">

	<!-- DAO rules	-->
	<rule name="DAO contract rule" priority="4"
		message="This DAO contract is not valid. Perhaps its name, package or type are wrong.">
		<filterPredicate xsi:type="jqa:AndPredicate">
			<predicate xsi:type="jqa:NamingPredicate" classNamePattern="**DAO*" />
			<predicate xsi:type="jqa:AbstractionPredicate"
				abstractionType="INTERFACE" />
		</filterPredicate>
		<checkPredicate xsi:type="jqa:ContextProvidedPredicate"
			providedPredicateName="Valid DAO contract" />
	</rule>
	
	<rule name="DAO implementation rule" priority="4"
		message="This DAO implementation is not valid. Perhaps its name, package or type are wrong.">
		<filterPredicate xsi:type="jqa:AndPredicate">
			<predicate xsi:type="jqa:NamingPredicate" classNamePattern="**DAO*" />
			<predicate xsi:type="jqa:AbstractionPredicate"
				abstractionType="CONCRETE" />
		</filterPredicate>
		<checkPredicate xsi:type="jqa:ContextProvidedPredicate"
			providedPredicateName="Valid DAO implementation" />
	</rule>

</jqa:Ruleset>
