=== fluxitsoft/jqa/jqa-parent/jqa-ctx-factory-xmlbeans/src/main/resources/schema/rulescontext.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  Copyright (c) 2013 Flux IT.
  
  This file is part of JQA (http://github.com/fluxitsoft/jqa).
  
  JQA is free software: you can redistribute it and/or modify it 
  under the terms of the GNU Lesser General Public License as 
  published by the Free Software Foundation, either version 3 of 
  the License, or (at your option) any later version.
  
  JQA is distributed in the hope that it will be useful, but WITHOUT 
  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General 
  Public License for more details.
  
  You should have received a copy of the GNU Lesser General Public 
  License along with JQA. If not, see <http://www.gnu.org/licenses/>.
-->
<xsd:schema xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:jqa="http://www.fluxit.com.ar/jqa/schema/ruleset" xmlns:jqa_ctx="http://www.fluxit.com.ar/jqa/schema/rulescontext" xmlns:xsd="http://www.w3.org/2001/XMLSchema" ecore:nsPrefix="jqa_ctx" ecore:package="jqa_ctx" targetNamespace="http://www.fluxit.com.ar/jqa/schema/rulescontext">
  <xsd:import namespace="http://www.fluxit.com.ar/jqa/schema/ruleset" schemaLocation="ruleset.xsd"/>
  <xsd:element ecore:ignore="true" name="RulesContext" type="jqa_ctx:RulesContext"/>
  <xsd:element ecore:ignore="true" name="RulesContextImport" type="jqa_ctx:RulesContextImport"/>
  <xsd:element ecore:ignore="true" name="GlobalVariable" type="jqa_ctx:GlobalVariable"/>
  <xsd:complexType name="RulesContext">
    <xsd:sequence>
      <xsd:element ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="rulesContextImport" type="jqa_ctx:RulesContextImport"/>
      <xsd:element ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="globalPredicate" type="jqa:Predicate"/>
      <xsd:element ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="ruleSet" type="jqa:Ruleset"/>
      <xsd:element ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="globalVariable" type="jqa_ctx:GlobalVariable"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string"/>
  </xsd:complexType>
  <xsd:complexType name="RulesContextImport">
    <xsd:attribute name="resource" type="xsd:string" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="GlobalVariable">
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="value" type="xsd:string" use="required"/>
  </xsd:complexType>
</xsd:schema>

=== fluxitsoft/jqa/jqa-parent/jqa-test-parent/jqa-test-project/src/main/resources/variables.xml
<?xml version="1.0" encoding="UTF-8"?>
<jqa_ctx:RulesContext name=""
	xmlns:jqa="http://www.fluxit.com.ar/jqa/schema/ruleset" xmlns:jqa_ctx="http://www.fluxit.com.ar/jqa/schema/rulescontext"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fluxit.com.ar/jqa/schema/rulescontext https://raw.github.com/jbaris/jqa/master/jqa-parent/jqa-ctx-factory-xmlbeans/src/main/resources/schema/rulescontext.xsd ">

	<!-- How implementations should be called -->
	<globalVariable name="entity.namePattern" value="**.entity.**" />
	<globalVariable name="serviceContract.namePattern" value="**.service.+Service" />
	<globalVariable name="boContract.namePattern" value="**.bo.+BO" />
	<globalVariable name="daoContract.namePattern" value="**.dao.+DAO" />

	<!-- How contracts should be called -->
	<globalVariable name="serviceImpl.namePattern" value="**.service.impl.+ServiceImpl" />
	<globalVariable name="boImpl.namePattern" value="**.bo.impl.+BOImpl" />
	<globalVariable name="daoImpl.namePattern" value="**.dao.impl.+DAOImpl" />

	<!-- Where the contracts should be located -->
	<globalVariable name="serviceContract.packagePattern" value="**.service.+" />
	<globalVariable name="boContract.packagePattern" value="**.bo.+" />
	<globalVariable name="daoContract.packagePattern" value="**.dao.+" />

	<!-- Where the implementations should be located -->
	<globalVariable name="serviceImpl.packagePattern" value="**.service.impl.+" />
	<globalVariable name="boImpl.packagePattern" value="**.bo.impl.+" />
	<globalVariable name="daoImpl.packagePattern" value="**.dao.impl.+" />

	<!-- Who should extend/implement the classes -->
	<globalVariable name="entity.superType" value="ar.com.fluxit.jqa.test.fmk.entity.Entity" />
	<globalVariable name="service.superType" value="ar.com.fluxit.jqa.test.fmk.service.Service" />
	<globalVariable name="bo.superType" value="ar.com.fluxit.jqa.test.fmk.bo.BusinessObject" />
	<globalVariable name="dao.superType" value="ar.com.fluxit.jqa.test.fmk.dao.DataAccessObject" />
	<globalVariable name="view.superType" value="ar.com.fluxit.jqa.test.fmk.view.View" />

	<!-- Who should extend/implement the exceptions -->
	<globalVariable name="serviceException.superType" value="ar.com.fluxit.jqa.test.fmk.service.ServiceException" />
	<globalVariable name="boException.superType" value="ar.com.fluxit.jqa.test.fmk.bo.BusinessObjectException" />
	<globalVariable name="daoException.superType" value="ar.com.fluxit.jqa.test.fmk.dao.DataAccessObjectException" />
	<globalVariable name="viewException.superType" value="ar.com.fluxit.jqa.test.fmk.view.ViewException" />

</jqa_ctx:RulesContext>

=== fluxitsoft/jqa/jqa-parent/jqa-test-parent/jqa-test-project/src/main/resources/rulesContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<jqa_ctx:RulesContext xmlns:jqa="http://www.fluxit.com.ar/jqa/schema/ruleset"
	xmlns:jqa_ctx="http://www.fluxit.com.ar/jqa/schema/rulescontext"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fluxit.com.ar/jqa/schema/rulescontext http://jqa-project.googlecode.com/svn/trunk/jqa-parent/jqa-ctx-factory/src/main/resources/schema/rulescontext.xsd ">

	<!-- Ruleset imports -->
	<rulesContextImport fileName="dao.xml" />
	<rulesContextImport fileName="bo.xml" />
	<rulesContextImport fileName="service.xml" />
	<rulesContextImport fileName="entity.xml" />

	<!-- DAO predicates -->
	<globalPredicate name="Valid DAO contract name" xsi:type="jqa:NamingPredicate"
		classNamePattern="**.dao.+DAO" />
		
	<globalPredicate name="Valid DAO implementation name" xsi:type="jqa:NamingPredicate"
		classNamePattern="**.dao.impl.+DAOImpl" />	
		
	<globalPredicate name="Valid DAO type" xsi:type="jqa:TypingPredicate">
		<filterPredicate xsi:type="jqa:NamingPredicate"
			classNamePattern="ar.com.fluxit.jqa.test.fmk.dao.DataAccessObject" />
	</globalPredicate>

	<!-- BO predicates -->
	<globalPredicate name="Valid BO contract name" xsi:type="jqa:NamingPredicate"
		classNamePattern="**.bo.+BO" />
		
	<globalPredicate name="Valid BO implementation name" xsi:type="jqa:NamingPredicate"
		classNamePattern="**.bo.impl.+BOImpl" />	
		
	<globalPredicate name="Valid BO type" xsi:type="jqa:TypingPredicate">
		<filterPredicate xsi:type="jqa:NamingPredicate"
			classNamePattern="ar.com.fluxit.jqa.test.fmk.bo.BusinessObject" />
	</globalPredicate>
	
	<!-- Service predicates -->
	<globalPredicate name="Valid Service contract name" xsi:type="jqa:NamingPredicate"
		classNamePattern="**.service.+Service" />
		
	<globalPredicate name="Valid Service implementation name" xsi:type="jqa:NamingPredicate"
		classNamePattern="**.service.impl.+ServiceImpl" />	
		
	<globalPredicate name="Valid Service type" xsi:type="jqa:TypingPredicate">
		<filterPredicate xsi:type="jqa:NamingPredicate"
			classNamePattern="ar.com.fluxit.jqa.test.fmk.service.Service" />
	</globalPredicate>
	
	<!-- Entity predicates -->
	<globalPredicate name="Valid Entity name" xsi:type="jqa:NamingPredicate"
		classNamePattern="**.entity.**" />
		
	<globalPredicate name="Valid Entity type" xsi:type="jqa:TypingPredicate">
		<filterPredicate xsi:type="jqa:NamingPredicate"
			classNamePattern="ar.com.fluxit.jqa.test.fmk.entity.Entity" />
	</globalPredicate>
	
</jqa_ctx:RulesContext>
